### ISSUE TITLE
🐛 `gen_motion_stats` not getting all necessary parameters

### ISSUE THREAD

**Issue by shnizzedy** [shnizzedy/C-PAC#2]
**Describe the bug**

https://github.com/shnizzedy/C-PAC/blob/33e22b281e907f1008da0371a15513047cfabd11/CPAC/pipeline/cpac_pipeline.py#L2202-L2218

```Python
200606-00:00:33,108 nipype.workflow ERROR:
	 could not run node: resting_preproc_2014113_1.gen_motion_stats_None_None_None_0.calc_motion_parameters.b0
```
```Python
200606-00:00:33,108 nipype.workflow ERROR:
	 could not run node: resting_preproc_2014113_1.gen_motion_stats_None_None_None_0.calc_power_parameters.b0
```
```Python
200606-00:00:33,109 nipype.workflow ERROR:
	 could not run node: resting_preproc_2014113_1.gen_motion_stats_None_None_None_0.calculate_FDJ
```

**Versions** 
 - C-PAC: https://github.com/FCP-INDI/C-PAC/commit/a9ae37ec31141d8700136c9cb1a5e40b178c52f4 ([Ⓢ](https://2244-4733263-gh.circle-artifacts.com/0/cpac-singularity-image.simg) [:whale:](https://2244-4733263-gh.circle-artifacts.com/0/cpac-docker-image.tar.gz))
 - Container Platform :
    - Singularity: 2.5.2

**Additional context**
This may be fixed in https://github.com/FCP-INDI/C-PAC/pull/1288

**Comment by shnizzedy** [comment]
Possibly related: https://github.com/FCP-INDI/C-PAC/issues/1149

**Comment by shnizzedy** [comment]
Update: not fixed in https://github.com/FCP-INDI/C-PAC/pull/1288 as evidenced by 

```python
200609-18:51:31,617 nipype.workflow ERROR:
	 could not run node: resting_preproc_2014113_1.gen_motion_stats_None_None_None_0.calc_motion_parameters.b0
```
```python
200609-18:51:31,617 nipype.workflow ERROR:
	 could not run node: resting_preproc_2014113_1.gen_motion_stats_None_None_None_0.calc_power_parameters.b0
```
```python
200609-18:51:31,617 nipype.workflow ERROR:
	 could not run node: resting_preproc_2014113_1.gen_motion_stats_None_None_None_0.calculate_FDJ
```
```python
200609-18:51:31,617 nipype.workflow ERROR:
	 could not run node: resting_preproc_2014113_1.nuisance_regressor_1_0.build_nuisance_regressors.a0.b0
```

When running 0e28e1c, which includes ea5f306:

```gitgraph
*   0e28e1c1 (HEAD -> fix/libGL.so.1, origin/fix/libGL.so.1) 🤝 Merge branch 'develop' into fix/libGL.so.1
|\  
* | a9ae37ec 🚑 Don't prefix TSV headers with #
* | 87818b6e 🔧 Set path to test artifacts for Docker tests
* | 47fd279d 🐍 Set Circle Python version @ 3.6.3
* | 95b8eea8 💚 Move Docker test to exec script
* | 142ffee6 💚 Install dependencies for Singularity test
| | * 7bffc6f9 (origin/feature/tissue_acpc) acpc reference
| | *   56f64d45 Merge remote-tracking branch 'origin/feature/acpc_align' into feature/tissue_acpc
| | |\  
| | | * 1df76e63 (origin/feature/acpc_align) Original ACPC alignment connections.
| | * 882f7c94 (origin/feature/tissue_ingress) Condense the peripheral anatomical datasources, and enable tissue mask ingress.
| |/  
| *   33e22b28 (origin/develop, develop) Merge pull request #1295 from FCP-INDI/fix/sinker
| |\  
| | * 6337d3c2 (origin/fix/sinker, fix/sinker) 📝 Cast `files` to an empty list before `ensure_list(files)` if files is None
| |/  
| | * cb9b0b33 (origin/hotfix/libGL.so.1, hotfix/libGL.so.1) 🚑 Don't prefix TSV headers with #
| | * a750cd98 🚑 Fix number of lines in censors.tsv (#1268)
| | * e27707c1 Ⓢ Specify file links for libGL and libgsl in Dockerfile
| | * 75c862ef Ⓢ Fancier libgsl linking
| | * 417fe3d3 🔧 Add ldconfig to Dockerfils
| | | * 55344778 (origin/feature/longitudinal) fix merge bug, delete unused nodes
| | | *   732e090a Merge branch 'develop' of https://github.com/FCP-INDI/C-PAC into feature/longitudinal
| | | |\  
| | |_|/  
| |/| |   
| * | | 8ee91a9d (improve/flatten_list) New regression test configs.
| * | |   1b3d628a Merge pull request #1288 from FCP-INDI/fix/motion_strat_update
| |\ \ \  
| | * | | ea5f306a (origin/fix/motion_strat_update) update motion strat resource pool
```

**Comment by shnizzedy** [comment]
```Python
Traceback (most recent call last):

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/linear.py", line 44, in run
    node.run(updatehash=updatehash)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)

  File "/code/CPAC/utils/interfaces/function.py", line 152, in _run_interface
    out = function_handle(**args)

  File "/code/CPAC/nuisance/nuisance.py", line 267, in gather_nuisance
    raise ValueError("Regressor type Censor specified in selectors but "

ValueError: Regressor type Censor specified in selectors but the corresponding file was not found!
```

**Comment by shnizzedy** [comment]
When we get to the block that's throwing the error

https://github.com/shnizzedy/C-PAC/blob/379277ebabdcff897d377ea23faed0721f9bef27/CPAC/nuisance/nuisance.py#L260-L269

`selector['Censor']` [looks like](https://50-271064270-gh.circle-artifacts.com/0/outputs/crash/crash-20200611-182320-circleci-build_nuisance_regressors.a0.b0-c485a0d4-f23b-45f4-8397-47e87177d7de.pklz)
```Python
{'method': 'SpikeRegression', 'number_of_previous_trs_to_censor': 1, 'number_of_subsequent_trs_to_censor': 2, 'thresholds': [{'type': 'FD_P', 'value': 0.5}]}
```

which seems reasonable.

**Comment by shnizzedy** [comment]
The whole `selector` looks like

```Python
{
	'Bandpass': {
		'bottom_frequency': 0.009,
		'top_frequency': 0.08
	},
	'Censor': {
		'method': 'SpikeRegression',
		'number_of_previous_trs_to_censor': 1,
		'number_of_subsequent_trs_to_censor': 2,
		'thresholds': [{
			'type': 'FD_P',
			'value': 0.5
		}]
	},
	'CerebrospinalFluid': {
		'erode_mask': True,
		'extraction_resolution': 2,
		'summary': {
			'filter': 'Mean',
			'method': 'Mean'
		}
	},
	'GlobalSignal': {
		'summary': {
			'filter': 'Mean',
			'method': 'Mean'
		}
	},
	'Motion': {
		'include_delayed': True,
		'include_delayed_squared': True,
		'include_squared': True
	},
	'PolyOrt': {
		'degree': 2
	},
	'WhiteMatter': {
		'erode_mask': True,
		'extraction_resolution': 2,
		'summary': {
			'filter': 'Mean',
			'method': 'Mean'
		}
	},
	'aCompCor': {
		'extraction_resolution': 2,
		'summary': {
			'components': 5,
			'method': 'DetrendPC'
		},
		'tissues': ['WhiteMatter', 'CerebrospinalFluid']
	}
}
```

**Comment by shnizzedy** [comment]
Progress (I think). With [the most recent image](https://178-271064270-gh.circle-artifacts.com/0/cpac-singularity-image.simg), I'm hitting the issue of empty `roi_stats.csv` files mentioned in https://github.com/FCP-INDI/C-PAC/issues/1140#issuecomment-575400720 & https://github.com/FCP-INDI/C-PAC/issues/1201#issuecomment-589827997

**Comment by shnizzedy** [comment]
Here's the full set of kwargs that are getting through:

```Python
{'functional_file_path': '/home/circleci/project/outputs/working/resting_preproc_A00040640_NFB3/func_preproc_afni_mean_3dvolreg_0/_scan_MSIT/func_normalize/sub-A00040640_ses-NFB3_task-MSIT_bold_calc_tshift_resample_volreg_calc_maths.nii.gz',
 'selector': {'Bandpass': {'bottom_frequency': 0.009, 'top_frequency': 0.08},
  'Censor': {'method': 'SpikeRegression',
   'number_of_previous_trs_to_censor': 1,
   'number_of_subsequent_trs_to_censor': 2,
   'thresholds': [{'type': 'FD_P', 'value': 0.5}]},
  'CerebrospinalFluid': {'erode_mask': True,
   'extraction_resolution': 2,
   'summary': {'filter': 'Mean', 'method': 'Mean'}},
  'GlobalSignal': {'summary': {'filter': 'Mean', 'method': 'Mean'}},
  'Motion': {'include_delayed': True,
   'include_delayed_squared': True,
   'include_squared': True},
  'PolyOrt': {'degree': 2},
  'WhiteMatter': {'erode_mask': True,
   'extraction_resolution': 2,
   'summary': {'filter': 'Mean', 'method': 'Mean'}},
  'aCompCor': {'extraction_resolution': 2,
   'summary': {'components': 5, 'method': 'DetrendPC'},
   'tissues': ['WhiteMatter', 'CerebrospinalFluid']}},
 'grey_matter_summary_file_path': None,
 'white_matter_summary_file_path': '/home/circleci/project/outputs/working/resting_preproc_A00040640_NFB3/nuisance_regressor_1_0/_scan_MSIT/_selector_WM-2mmE-M_CSF-2mmE-M_aC-CSF+WM-2mm-DPC5_G-M_M-SDB_P-2_BP-B0.009-T0.08_C-S-1+2-FD-P0.5/WhiteMatter_mean/roi_stats.csv',
 'csf_summary_file_path': '/home/circleci/project/outputs/working/resting_preproc_A00040640_NFB3/nuisance_regressor_1_0/_scan_MSIT/_selector_WM-2mmE-M_CSF-2mmE-M_aC-CSF+WM-2mm-DPC5_G-M_M-SDB_P-2_BP-B0.009-T0.08_C-S-1+2-FD-P0.5/CerebrospinalFluid_mean/roi_stats.csv',
 'acompcor_file_path': '/home/circleci/project/outputs/working/resting_preproc_A00040640_NFB3/nuisance_regressor_1_0/_scan_MSIT/_selector_WM-2mmE-M_CSF-2mmE-M_aC-CSF+WM-2mm-DPC5_G-M_M-SDB_P-2_BP-B0.009-T0.08_C-S-1+2-FD-P0.5/aCompCor_DetrendPC/compcor_regressors.1D',
 'tcompcor_file_path': None,
 'global_summary_file_path': '/home/circleci/project/outputs/working/resting_preproc_A00040640_NFB3/nuisance_regressor_1_0/_scan_MSIT/_selector_WM-2mmE-M_CSF-2mmE-M_aC-CSF+WM-2mm-DPC5_G-M_M-SDB_P-2_BP-B0.009-T0.08_C-S-1+2-FD-P0.5/GlobalSignal_mean/roi_stats.csv',
 'motion_parameters_file_path': '/home/circleci/project/outputs/working/resting_preproc_A00040640_NFB3/func_preproc_afni_mean_3dvolreg_0/_scan_MSIT/func_motion_correct_3dvolreg/sub-A00040640_ses-NFB3_task-MSIT_bold_calc_tshift_resample.1D',
 'custom_file_paths': None,
 'censor_file_path': None}
```

**Comment by shnizzedy** [comment]
This issue is resolved in https://github.com/FCP-INDI/C-PAC/pull/1288 + https://github.com/FCP-INDI/C-PAC/pull/1289 + https://github.com/FCP-INDI/C-PAC/pull/1304 + https://github.com/FCP-INDI/C-PAC/pull/1305
